const TYPES = {
    SET_CONTEXT: "SET_CONTEXT",
    SET_SINK: "SET_SINK",
    UPDATE_INPUT: "UPDATE_INPUT",
    CLEAR_INPUT: "CLEAR_INPUT",
    TOGGLE_INPUT: "TOGGLE_INPUT",
    CLEAR_AUDIO: "CLEAR_AUDIO"
}

module.exports = TYPES;