const TYPES = {
    SET_CONTEXT: "SET_CONTEXT",
    SET_SINK: "SET_SINK",
    UPDATE_INPUT: "UPDATE_INPUT",
    CLEAR_INPUT: "CLEAR_INPUT",
    UPDATE_MET_INPUT: "UPDATE_MET_INPUT",
    CLEAR_MET_INPUT: "CLEAR_MET_INPUT",
    TOGGLE_INPUT: "TOGGLE_INPUT",
    CLEAR_AUDIO: "CLEAR_AUDIO",
    SET_SINK_VOL: "SET_SINK_VOL"
}

module.exports = TYPES;